name: Add Colab Badges to notebooks
on: [push]

jobs:
    badges:
        name: Example Badge Job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout first
              id: checkout
              uses: actions/checkout@v2

            - name: Add/Update badges
              id: badges
              uses: trsvchn/colab-badge-action@v4
              with:
                check: "all"
                target_branch: master
                target_repository: AMasetti/AI-Portfolio-Examples
                update: true


            - name: Commit and Push
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: "Add Colab Badges"
              env:
                GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
